parameters:
    evilpope_tagging.tag_manager.class: Evilpope\TaggingBundle\Service\TagManager

services:
    evilpope_tagging.form.tags:
        class: Evilpope\TaggingBundle\Form\TagsType
        arguments: [ "@fpn.tag_manager" ]
        tags:
            - { name: form.type, alias: tags }
            
    evilpope_tagging.taggable.subscriber:
        class: Evilpope\TaggingBundle\EventListener\TaggableSubscriber
        arguments: [ '@service_container', 'fpn.tag_manager' ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }