parameters:
    fpn_tag.tag_manager.class: Evilpope\TaggingBundle\Service\TagManager

services:
    evilpope_tag.form.tags:
        class: Evilpope\TaggingBundle\Form\TagsType
        arguments: [ "@evilpope_tag.tag_manager" ]
        tags:
            - { name: form.type, alias: tags }
            
    evilpope_tag.taggable.subscriber:
        class: Evilpope\TaggingBundle\EventListener\TaggableSubscriber
        arguments: [ '@service_container', 'evilpope_tag.tag_manager' ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }